### PR TITLE
Remove unused imports and use a non-pointer reader

### LINKED ISSUE #95: cannot use file (type *io.Reader) as type io.Reader in argument to io.Copy
Hey @JonasFranzDEV, I get the following compilation error using the latest [commit](https://github.com/go-gitea/go-sdk/commit/c026786979c62f631658f365fd26e277cd90bfa4):

```
# bitbucket.org/gridarrow/gridarrow-manager/vendor/code.gitea.io/sdk/gitea
vendor/code.gitea.io/sdk/gitea/attachment.go:11:2: imported and not used: "io/ioutil"
vendor/code.gitea.io/sdk/gitea/attachment.go:58:21: cannot use file (type *io.Reader) as type io.Reader in argument to io.Copy:
	*io.Reader is pointer to interface, not interface
```

This is with the following glide dependency:
```
- package: code.gitea.io/sdk
  subpackages:
  - gitea
```

Previous commit works fine for me. Not a go expert, so perhaps it's my bad somehow...

### PR DESCRIPTION
**Pull request by jonasfranz**
Fix #95 by removing unused imports and using a non-pointer reader

Bug was introduced by #90.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]
